import theme from "antd/lib/theme";
import alias from "antd/lib/theme/util/alias";

function main() {
  const { defaultSeed, defaultAlgorithm, darkAlgorithm, compactAlgorithm } =
    theme;

  const result = {
    default: alias({ ...defaultAlgorithm(defaultSeed), override: {} }),
    dark: alias({ ...darkAlgorithm(defaultSeed), override: {} }),
    compact: alias({ ...compactAlgorithm(defaultSeed), override: {} }),
  };

  const output = `\
// auto-generated by build-theme.ts
// prettier-ignore
export const theme = ${JSON.stringify(result, null, 2)};
`;
  console.log(output);
}

main();
