name: release-lib
on:
  push:
jobs:
  release-lib:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 7
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: pnpm
      - run: pnpm i --frozen-lockfile
      - run: pnpm build-lib
      - name: setup .npmrc with NPM_TOKEN
        run: |
          echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' >> .npmrc
      - run: pnpm release-lib
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
