# required secrets
# - VERCEL_ORG_ID
# - VERCEL_PROJECT_ID
# - VERCEL_TOKEN

# references
# - https://vercel.com/guides/how-can-i-use-gitlab-pipelines-with-vercel
# - https://docs.github.com/en/actions/security-guides/encrypted-secrets#creating-encrypted-secrets-for-a-repository

name: release
on:
  push:
jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 7
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: pnpm
      - run: pnpm i --frozen-lockfile
      - run: pnpm build-lib
      - run: pnpm build
      - run: npm i -g vercel@25.2.3
      - run: bash packages/app/misc/vercel/ci-setup.sh
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      - run: pnpm release
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
