name: release-lib
on:
  push:
jobs:
  release-lib:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 7
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: pnpm
      - run: pnpm i --frozen-lockfile
      - run: pnpm build-lib
      - run: pnpm release-lib
        env:
          # actions/setup-node creates .npmrc https://github.com/actions/setup-node/blob/3dbcda8bc2eb5ec6aa3fbde01feaae3236952db8/src/authutil.ts#L48
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
